### ISSUE TITLE
Practica 7_Edwin, Ivan, Alexis, Taoli

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/practica-de-gps-equipo_cafe-huerto-el-mamey#2]
[Practica 7_Edwin, Ivan, Alexis, Taoli.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-gps-equipo_cafe-huerto-el-mamey/files/8617980/Practica.7_Edwin.Ivan.Alexis.Taoli.pdf)

**Comment by claudiasilvavenda** [comment]
La calif. es 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
